Add Echo to Ruby
teknologi-umum/pehape pull request #15
Opened 2022-03-20 03:11 UTC by afman42

Implementation
- string
  - [x] echo

unit test
- string
  - [x] echo

2022-03-24 16:25 UTC, ronnygunawan requested changes
Testnya belum ngetest apa-apa. Mungkin bisa pake cara ini: https://stackoverflow.com/questions/16507067/testing-stdout-output-in-rspec

2022-03-24 21:52 UTC, elianiva requested changes

2022-03-24 21:52 UTC, elianiva commented on ruby/spec/pehape/string/echo_spec.rb
> +    expect(Pehape.echo("Pe ha pe")).to equal(nil)
assert stdoutnya, jangan return valuenya
http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#new-output-matcher

2022-03-26 04:36 UTC, afman42 commented
oke om, makasih sarannya

2022-03-26 04:58 UTC, afman42 commented
bisa di cek output di command `bin/console` dan `Pehape.echo(blabla)`. om @ronnygunawan

2022-03-26 12:23 UTC, ronnygunawan approved these changes
Nice! LGTM

2022-03-26 12:24 UTC, merged