feat(rust): add implode and explode
teknologi-umum/pehape pull request #24
Opened 2022-04-02 03:24 UTC by elianiva

ngga tau CI bakal jalan atau ngga

2022-04-02 06:25 UTC, aldy505 approved these changes

2022-04-02 06:48 UTC, elianiva commented
note to self: coba implement caching buat github action, ini yg bikin CI lama gara gara harus compile grcov

2022-04-02 15:29 UTC, aldy505 commented
> note to self: coba implement caching buat github action, ini yg bikin CI lama gara gara harus compile grcov

no prob, ini repo open source. kalo CI takes time, ngga masalah.

2022-04-03 15:09 UTC, ronnygunawan requested changes

2022-04-04 02:14 UTC, ronnygunawan approved these changes

2022-04-04 02:15 UTC, merged