Add lcfirst,ucfirst to ruby
teknologi-umum/pehape pull request #26
Opened 2022-04-02 14:04 UTC by afman42

Example test:
- lcfirst
https://www.w3schools.com/php/phptryit.asp?filename=tryphp_func_string_lcfirst
- ucfirst
https://www.w3schools.com/php/phptryit.asp?filename=tryphp_func_string_ucfirst

- string
  - [x] lcfirst
  - [x] ucfirst
- unit test
  - [x] lcfirst
  - [x] ucfirst

2022-04-02 14:05 UTC, afman42 commented
silakan di cek om @ronnygunawan @elianiva @aldy505

2022-04-02 14:15 UTC, elianiva requested changes

2022-04-02 14:15 UTC, elianiva commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("PeHaPe")).to eq("peHaPe")
jangan lupa test pake karakter aneh aneh kaya `ü`, `ä`, dll

2022-04-02 14:15 UTC, elianiva commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
di PHP ini hasilnya tetep `  PeHaPe  HE   `, jangan strip whitespacenya

2022-04-02 14:18 UTC, afman42 commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
Tapi kak kalau tidak di strip ada whitespace nya kak

2022-04-02 14:19 UTC, afman42 commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("PeHaPe")).to eq("peHaPe")
Iya kak

2022-04-02 14:25 UTC, elianiva commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
iya gpp, emang gitu behaviour aslinya di PHP

2022-04-02 15:27 UTC, afman42 commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
Ok kak

2022-04-03 05:35 UTC, afman42 commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
kalau saya hapus strip jadi ada whitespace dan juga errror kode nya juga

2022-04-03 05:36 UTC, afman42 commented
cek om @ronnygunawan @elianiva

2022-04-04 22:48 UTC, elianiva commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +    expect(Pehape.lcfirst("  PeHaPe  HE   ")).to eq("peHaPe  HE")
iya gpp ada whitespacenya, di PHP emang gitu

2022-04-05 07:54 UTC, ronnygunawan requested changes
Grammar fixes. Langsung aja add suggestion to batch

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +  it "first character lowercase" do
```suggestion
  it "converts first character to lowercase" do
```

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +  it "remove left and right whitespace and get first character lowercase" do
```suggestion
  it "removes leading and trailing whitespace and converts first character to lowercase" do
```

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +  it "another character except abjad and get first character lowercase" do
```suggestion
  it "converts non-english first character to lowercase" do
```

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/ucfirst_spec.rb
> +  it "remove left whitespace and get first character uppercase" do
```suggestion
  it "removes leading whitespace and converts first character to uppercase" do
```

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/ucfirst_spec.rb
> +  it "remove left and right whitespace and get first character uppercase" do
```suggestion
  it "removes leading and trailing whitespace and converts first character to uppercase" do
```

2022-04-05 07:54 UTC, ronnygunawan commented on ruby/spec/pehape/string/ucfirst_spec.rb
> +  it "another character except abjad and get first character uppercase" do
```suggestion
  it "converts non-english first character to uppercase" do
```

2022-04-06 10:04 UTC, elianiva commented on ruby/lib/pehape/string/lcfirst.rb
> +    str.sub(/^(\w)/, &:downcase)
kenapa sampe pake regex?

2022-04-06 10:36 UTC, afman42 commented on ruby/lib/pehape/string/lcfirst.rb
> +    str.sub(/^(\w)/, &:downcase)
Pakai cara tercepat kak

2022-04-06 16:52 UTC, ronnygunawan commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
kenapa sampe pake regex? (2)

2022-04-06 21:59 UTC, afman42 commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
Itu cara tercepat aja om. Kalau saya ubah lagi lebih panjang lagi. Apakah punya saran om?

2022-04-07 02:15 UTC, ronnygunawan commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
coba:

```ruby
str.strip.capitalize
```

2022-04-07 04:36 UTC, afman42 commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
Kata kak @elianiva gak boleh pakai strip karena ada test whitespace nya om

2022-04-07 04:45 UTC, ronnygunawan commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
Oh iya juga. ada solusi @elianiva ?

2022-04-07 09:02 UTC, elianiva commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
cara awal sebenernya udah bisa, cuma ga perlu di-strip, tapi clone aja stringnya kaya gini:

```ruby
def lcfirst(str)
   dup = str
   dup[0] = dup[0].downcase
   dup
end
```

2022-04-09 07:17 UTC, afman42 commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
Tidak work kak @elianiva

2022-04-09 09:02 UTC, elianiva commented on ruby/lib/pehape/string/ucfirst.rb
> +    str.sub(/^(\w)/, &:capitalize)
bisa kok
![image](https://user-images.githubusercontent.com/51877647/162564673-059ecb62-f84e-44a7-a970-4e71e12a68a1.png)

2022-04-10 07:33 UTC, afman42 commented
silakan di cek om @ronnygunawan dan @elianiva

2022-04-10 09:19 UTC, elianiva commented on ruby/lib/pehape/string/ucfirst.rb
> +    stra = str
kasih nama yg lebih descriptive, `stra` ini apa?

2022-04-10 11:39 UTC, afman42 commented on ruby/lib/pehape/string/ucfirst.rb
> +    stra = str
Di cek lagi kak

2022-04-10 11:39 UTC, afman42 commented on ruby/lib/pehape/string/ucfirst.rb
> +    stra = str
@elianiva

2022-04-10 13:16 UTC, elianiva approved these changes
sisa benerin testnya, udah ada review diatas

2022-04-13 12:20 UTC, afman42 commented
Cek om @ronnygunawan

2022-04-14 03:21 UTC, ronnygunawan requested changes
Bersih bersih test description

2022-04-14 03:21 UTC, ronnygunawan commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +  it "remove leading whitespace and get first character to lowercase" do
```suggestion
  it "removes leading whitespace and converts first character to lowercase" do
```

2022-04-14 03:21 UTC, ronnygunawan commented on ruby/spec/pehape/string/lcfirst_spec.rb
> +  it "remove leading and trailing whitespace and converts first character to lowercase" do
```suggestion
  it "removes leading and trailing whitespace and converts first character to lowercase" do
```

2022-04-14 03:21 UTC, ronnygunawan commented on ruby/spec/pehape/string/ucfirst_spec.rb
> +  it "remove leading whitespace and converts first character to uppercase" do
```suggestion
  it "removes leading whitespace and converts first character to uppercase" do
```

2022-04-14 03:21 UTC, ronnygunawan commented on ruby/spec/pehape/string/ucfirst_spec.rb
> +  it "converts non-english first character to  uppercase" do
```suggestion
  it "converts non-english first character to uppercase" do
```

2022-04-14 15:59 UTC, afman42 commented
cek lagi ya om

2022-04-19 17:47 UTC, ronnygunawan approved these changes

2022-04-19 17:47 UTC, merged