Typescript/addslashes
teknologi-umum/pehape pull request #38
Opened 2022-10-01 01:43 UTC by mnasruul

First PR

2022-10-01 01:51 UTC, mnasruul commented
@aldy505 ini gimana ya pak, buildnya gagal.

2022-10-01 09:36 UTC, elianiva commented
CI abaikan aja, #41

2022-10-01 09:39 UTC, elianiva approved these changes
LGTM

2022-10-04 00:06 UTC, aldy505 requested changes
package lock nya apus, pakai pnpm aja kayak yang udah di establish di implementationnya.

2022-10-07 02:37 UTC, mnasruul commented
Done pak @aldy505

2022-10-08 02:25 UTC, aldy505 approved these changes

2022-10-08 02:25 UTC, merged