Feat-Go: add LTrim and RTrim function
teknologi-umum/pehape pull request #39
Opened 2022-10-01 03:42 UTC by YogiPristiawan

2022-10-01 04:37 UTC, elianiva commented
belum support range kaya PHP. See: https://www.php.net/manual/en/function.rtrim

![image](https://user-images.githubusercontent.com/51877647/193392729-b59430ff-cc38-46c8-9140-4beb46571721.png)

2022-10-01 06:34 UTC, YogiPristiawan commented
> belum support range kaya PHP. See: https://www.php.net/manual/en/function.rtrim
> 
> ![image](https://user-images.githubusercontent.com/51877647/193392729-b59430ff-cc38-46c8-9140-4beb46571721.png)

haruskah dihandle untuk range juga?

2022-10-01 09:45 UTC, elianiva commented
iya, biar behaviournya sama kaya yg ada di PHP

2022-10-01 16:30 UTC, YogiPristiawan commented
> > haruskah dihandle untuk range juga?
> 
> iya, biar behaviournya sama kaya yg ada di PHP

done at https://github.com/teknologi-umum/pehape/pull/39/commits/e9cbb0b029d43e235a301a0a36256c264d43e611

2022-10-03 01:24 UTC, aldy505 requested changes

2022-10-03 01:24 UTC, aldy505 commented on go/readme.md
> +- `Ucwords`
markdown nggak konsisten dengan function-function yang ada di atasnya.

2022-10-03 01:44 UTC, YogiPristiawan commented on go/readme.md
> +- `Ucwords`
bukan ga konsisten pak, Itu saya ganti `*` jadi heading `###` biar agak rapi

2022-10-03 01:47 UTC, aldy505 commented on go/readme.md
> +- `Ucwords`
Iya ini yang Ucwords masih `-` bukan `##`

2022-10-03 01:47 UTC, aldy505 commented
@YogiPristiawan ada merge conflict

2022-10-03 01:51 UTC, aldy505 approved these changes

2022-10-03 01:55 UTC, YogiPristiawan commented on go/readme.md
> +- `Ucwords`
done pak sudah saya update

2022-10-03 12:14 UTC, elianiva reviewed
ngga sekalian yg Trim?

2022-10-03 12:23 UTC, YogiPristiawan commented
> ngga sekalian yg Trim?
yg trim kenapa pak?

2022-10-03 15:25 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
jangan `tt` dong ;D

2022-10-03 15:25 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
[2] ini juga ;D

2022-10-03 15:25 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
-[3] ini juga

2022-10-03 15:25 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
[4]

2022-10-03 15:25 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
[5]

2022-10-03 15:25 UTC, WahidinAji commented on go/r_trim_test.go
> +		tt := &test{
[6]

2022-10-03 15:25 UTC, WahidinAji commented on go/r_trim_test.go
> +		tt := &test{
[7]

2022-10-03 15:25 UTC, WahidinAji commented on go/r_trim_test.go
> +		tt := &test{
[8]

2022-10-03 15:25 UTC, WahidinAji commented on go/r_trim_test.go
> +		tt := &test{
[9]

2022-10-03 15:25 UTC, WahidinAji commented on go/r_trim_test.go
> +		tt := &test{
[10]

2022-10-04 02:04 UTC, WahidinAji requested changes

2022-10-04 02:04 UTC, WahidinAji commented on go/l_trim_test.go
> +		res, err := PHP.LTrim(tt.param.str)
- [2]
```suggestion
res, err := PHP.LTrim(record.param.str)
```

2022-10-04 02:04 UTC, WahidinAji commented on go/l_trim_test.go
> +		if res != tt.expect {
- [3]
```suggestion
if res != record.expect {
```

2022-10-04 02:04 UTC, WahidinAji commented on go/l_trim_test.go
> +			t.Errorf("expected %s, but got %s", tt.expect, res)
- [4]
```suggestion
       t.Errorf("expected %s, but got %s", record.expect, res)
```

2022-10-04 02:04 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
masih belum diubah ;D

jangan lupa bagian [ini](https://github.com/teknologi-umum/pehape/pull/39/files#diff-07ea05941f027a02fb5acb178a984baefb5b3d39d724e7bb0e6139e688cf46cbR44-R50)

2022-10-04 02:04 UTC, WahidinAji commented on go/l_trim_test.go
> +		tt := &test{
`tt` [ini](https://github.com/teknologi-umum/pehape/pull/39/files#diff-07ea05941f027a02fb5acb178a984baefb5b3d39d724e7bb0e6139e688cf46cbR61-R67) jangan lupa

2022-10-06 10:40 UTC, aldy505 commented
ada merge conflict

2022-10-09 13:31 UTC, elianiva approved these changes

2022-10-10 03:05 UTC, merged