feat: add levenshtein implementation
teknologi-umum/pehape pull request #42
Opened 2022-10-01 16:07 UTC by fadilaaaa

this algo gives O(m*n) complexity

2022-10-01 18:05 UTC, WahidinAji commented
please, update the usage in the readme.md :D

2022-10-01 18:36 UTC, fadilaaaa commented
> please, update the usage in the readme.md :D

done sir (●'◡'●)

2022-10-02 02:22 UTC, aldy505 commented
@fadilaaaa there's a merge conflict

2022-10-02 02:26 UTC, aldy505 requested changes

2022-10-02 02:26 UTC, aldy505 commented on go/levenshtein.go
> +// LevenshteinDistance calculate the distance between two string
```suggestion
// Levenshtein calculates the distance between two strings.
```

2022-10-02 02:26 UTC, aldy505 commented on go/readme.md
> + fmt.Println(pehape.Levenshtein(str1,str2,insertion_cost,replacement_cost,deletion_cost))
please format the code

2022-10-02 02:26 UTC, aldy505 commented on go/readme.md
> + fmt.Println(pehape.Levenshtein(str1,str2))
```suggestion
 fmt.Println(pehape.Levenshtein(str1, str2))
```

2022-10-02 02:26 UTC, aldy505 commented on go/readme.md
> + deletion_cost := 3
don't use snake_case. use camelCase instead

2022-10-02 07:06 UTC, aldy505 approved these changes

2022-10-03 01:24 UTC, merged