Feat-Go: add StrSplit function
teknologi-umum/pehape pull request #44
Opened 2022-10-01 17:37 UTC by YogiPristiawan

2022-10-03 01:53 UTC, aldy505 requested changes

2022-10-03 01:53 UTC, aldy505 commented on go/str_split.go
> +// The str_split() function splits a string into an array.
```suggestion
// StrSplit splits a string into an array.
```

2022-10-03 01:53 UTC, aldy505 commented on go/str_split_test.go
> +		}
di cek juga value `err` isinya apa

2022-10-03 02:07 UTC, YogiPristiawan commented on go/str_split_test.go
> +		}
done

2022-10-03 15:11 UTC, WahidinAji commented on go/str_split.go
> +func StrSplit(str string, segLength ...int) (res []string, err error) {
ini dibuat `naked return` ajasih, dari pada `named return`. biar konsisten sama yg lain aja

```suggestion
func StrSplit(str string, segLength ...int) ([]string, error)
```

2022-10-03 15:11 UTC, WahidinAji commented on go/str_split_test.go
> +		tt := &test{
ini kalo bisa jangan `tt` sih, dalam pengucapan ini bisa salah arti

2022-10-03 15:11 UTC, WahidinAji commented on go/str_split_test.go
> +		tt := &test{
[2] ini juga :"

2022-10-03 15:11 UTC, WahidinAji commented on go/str_split_test.go
> +		tt := &test{
[3] ini juga :"

2022-10-03 15:38 UTC, YogiPristiawan commented on go/str_split_test.go
> +		tt := &test{
wkwk

2022-10-03 22:12 UTC, elianiva commented on go/str_split.go
> +func StrSplit(str string, segLength ...int) (res []string, err error) {
naked return sama named return itu sama aja pak wkwkwk

2022-10-04 00:08 UTC, aldy505 approved these changes

2022-10-04 01:24 UTC, YogiPristiawan commented on go/str_split.go
> +func StrSplit(str string, segLength ...int) (res []string, err error) {
okee

2022-10-05 05:54 UTC, elianiva approved these changes

2022-10-05 06:07 UTC, YogiPristiawan commented
kak @elianiva @aldy505 ini ada conflict. `str_split` nya mau pakai yg mana ya?

2022-10-06 10:37 UTC, aldy505 commented
keduluan berarti. ini close aja gapapa?

2022-10-06 12:08 UTC, YogiPristiawan commented
> keduluan berarti. ini close aja gapapa?

functionnya simple yg ini kayaknya pak. tapi monggo ding mau yg mana

2022-10-08 02:26 UTC, closed without merging