Initial Folder Ruby
teknologi-umum/pehape pull request #5
Opened 2022-03-18 14:38 UTC by afman42

# Implementation

- string
 - [x] explode

# Unit Test
- string
 - [ ] explode
 
please review it. om @aldy505 @ronnygunawan

2022-03-18 15:13 UTC, ronnygunawan requested changes
Selain change request di bawah, tolong ubah juga:
- [x] Struktur foldernya langsung aja di `ruby` ngga usah `ruby/php-func-ruby`
- [x] Gemspec taruh di `ruby/pehape.gemspec` dengan `spec.name` set ke "pehape"
- [x] Source root foldernya `ruby/lib`, ngga perlu sedalam `ruby/php-func-ruby/lib/php/func/ruby`
- [x] Modulenya cukup `Pehape`, ngga perlu sepanjang `Php::Func::Ruby`
- [x] Jangan lupa unit test

2022-03-18 15:13 UTC, ronnygunawan commented on ruby/php-func-ruby/lib/php/func/ruby/string/explode.rb
> +            end
Bisa dibikin lebih idiomatic:

```ruby
raise ArgumentError.new("Separator cannot be nil") if separator.nil?
```

2022-03-18 15:13 UTC, ronnygunawan commented on ruby/php-func-ruby/lib/php/func/ruby/string/explode.rb
> +            end
Bisa dibikin lebih idiomatic:

```ruby
raise ArgumentError.new("String cannot be nil") if string.nil?
```

2022-03-18 15:18 UTC, ronnygunawan requested changes
Tadi ada yang ketinggalan. explode tanpa parameter ketiga harusnya nggak throw exception dan nggak dilimit.

2022-03-18 15:18 UTC, ronnygunawan commented on ruby/php-func-ruby/lib/php/func/ruby/string/explode.rb
> +        def self.explode(separator,string,limit = nil)
```suggestion
        def self.explode(separator,string,limit = Integer.MAX)
```

2022-03-18 15:42 UTC, aldy505 requested changes

2022-03-18 15:42 UTC, aldy505 commented on ruby/php-func-ruby/php-func-ruby.gemspec
> +  spec.name = "php-func-ruby"
nama librarynya udah cross check dengan yang available di Gem repository?

2022-03-18 15:42 UTC, aldy505 commented on ruby/php-func-ruby/php-func-ruby.gemspec
> +  spec.version = Php::Func::Ruby::VERSION
ini bisa di hardcode.

2022-03-18 15:42 UTC, aldy505 commented on ruby/php-func-ruby/.gitignore
> +.rspec_status
bisa ambil dari websitenya toptal 

https://www.toptal.com/developers/gitignore

2022-03-18 15:42 UTC, aldy505 commented on ruby/php-func-ruby/lib/php/func/ruby.rb
> +      end
ini gaperlu. ga sesuai spesifikasi pehape.

2022-03-19 05:43 UTC, afman42 commented on ruby/php-func-ruby/lib/php/func/ruby/string/explode.rb
> +        def self.explode(separator,string,limit = nil)
`Integer.MAX` gak ada om methodnya

2022-03-19 06:44 UTC, afman42 commented
cek lagi om @aldy505 @ronnygunawan

2022-03-19 09:12 UTC, ronnygunawan commented
@afman42 Saya udah bikin koreksi di branch [teknologi-umum:ruby-suggestions](https://github.com/teknologi-umum/pehape/tree/ruby-suggestions). Coba kamu fetch upstream lalu merge ke branch kamu.

2022-03-19 10:12 UTC, ronnygunawan commented
Saya udah bikinin suggestions di https://github.com/afman42/pehape/pull/1

2022-03-19 10:40 UTC, afman42 commented
udah saya tambahkan siimplecov. silakan di cek om @ronnygunawan @aldy505

2022-03-19 12:22 UTC, aldy505 approved these changes

2022-03-19 12:25 UTC, ronnygunawan requested changes

2022-03-19 12:25 UTC, ronnygunawan commented on .github/workflows/pr_ruby.yml
> +      - name: Report coverage
Step ini tolong dihapus karena ternyata udah direport di step sebelumnya

2022-03-19 12:25 UTC, ronnygunawan commented on .github/workflows/pr_ruby.yml
> +      - name: Test
Ini direname aja soalnya ternyata step ini juga report ke codecov
```suggestion
      - name: Test and report coverage
```

2022-03-19 12:31 UTC, ronnygunawan approved these changes
Done

2022-03-19 12:33 UTC, merged