Go/php
teknologi-umum/pehape pull request #61
Opened 2022-10-04 04:22 UTC by YogiPristiawan

- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number: 

- [x] I have created unit tests to support my implementation
- [x] I have created in-code documentation (or docstring) to document my code
- [ ] (Optional) I have updated the README.md file to document the function I'm implementing

2022-10-04 05:04 UTC, elianiva commented on go/lcfirst.go
> +	for _, val := range str {
kenapa harus pake loop? ngga ambil index 0 aja?

2022-10-04 05:10 UTC, YogiPristiawan commented on go/lcfirst.go
> +	for _, val := range str {
buat prevent kalau parameternya empty string. hmm mungkin masih bisa direfactor ya. kucoba dulu

2022-10-04 07:02 UTC, aldy505 requested changes

2022-10-04 07:02 UTC, aldy505 commented on go/strchr.go
> +	}
jangan gini. gini aja:

```go
switch val := search.(type) {
case int:
  // handle
case string:
 // handle
default:
  // handle
}
```

2022-10-04 07:10 UTC, YogiPristiawan commented on go/lcfirst.go
> +	}
oke noted

2022-10-04 08:26 UTC, YogiPristiawan commented on go/lcrifst_test.go
> +		}
done

2022-10-05 05:53 UTC, elianiva approved these changes

2022-10-05 05:53 UTC, merged