feat: add StrReplace function
teknologi-umum/pehape pull request #64
Opened 2022-10-06 12:37 UTC by YogiPristiawan

- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number: 

- [x] I have created unit tests to support my implementation
- [x] I have created in-code documentation (or docstring) to document my code
- [ ] (Optional) I have updated the README.md file to document the function I'm implementing

Ini condisinya banyak sekali, semangat reviewer! :)

2022-10-10 03:11 UTC, aldy505 requested changes

2022-10-10 03:11 UTC, aldy505 commented on go/str_replace.go
> +
newline bikin documentation ajdi putus

2022-10-10 03:11 UTC, aldy505 commented on go/str_replace.go
> +					strCopy = strings.ReplaceAll(strCopy, find.(string), charsReplace)
kalo ujung-ujungnya perlu re-assert type nya gini, mending jangan pake reflex, di switch type aja

2022-10-10 03:11 UTC, aldy505 commented on go/str_replace.go
> +				if c := strings.Count(strCopy, find.(string)); c > 0 {
kalo ujung-ujungnya perlu re-assert type nya gini, mending jangan pake reflex, di switch type aja

2022-10-10 03:11 UTC, aldy505 commented on go/str_replace.go
> +				if find.(string) == "" {
kalo ujung-ujungnya perlu re-assert type nya gini, mending jangan pake reflex, di switch type aja

2022-10-10 03:38 UTC, YogiPristiawan commented on go/str_replace.go
> +				if find.(string) == "" {
oke pak

2022-10-10 03:39 UTC, YogiPristiawan commented
sorry salah pencet pak

2023-10-07 03:50 UTC, YogiPristiawan commented on go/str_replace.go
> +
done https://github.com/teknologi-umum/pehape/pull/64/commits/5b2c35357dfd4aae2d5420fc69dce82710f2cb6b

2023-10-07 03:51 UTC, YogiPristiawan commented on go/str_replace.go
> +					strCopy = strings.ReplaceAll(strCopy, find.(string), charsReplace)
done https://github.com/teknologi-umum/pehape/pull/64/commits/2f1c637223d1b96587640f89fa05691e1b4687ba

2023-10-07 03:51 UTC, YogiPristiawan commented on go/str_replace.go
> +				if c := strings.Count(strCopy, find.(string)); c > 0 {
done https://github.com/teknologi-umum/pehape/pull/64/commits/2f1c637223d1b96587640f89fa05691e1b4687ba

2023-10-07 03:51 UTC, YogiPristiawan commented on go/str_replace.go
> +				if find.(string) == "" {
done https://github.com/teknologi-umum/pehape/pull/64/commits/2f1c637223d1b96587640f89fa05691e1b4687ba

2023-10-07 03:55 UTC, aldy505 approved these changes

2023-10-07 03:55 UTC, merged