feat-typescript: add chr
teknologi-umum/pehape pull request #66
Opened 2022-10-07 06:46 UTC by afman42

- Programming langugage: typescript
- Function(s) that I'm implementing: chr
- Issue number: 

- [x] I have created unit tests to support my implementation
- [x] I have created in-code documentation (or docstring) to document my code
- [ ] (Optional) I have updated the README.md file to document the function I'm implementing

2022-10-08 04:31 UTC, aldy505 requested changes

2022-10-08 04:31 UTC, aldy505 commented on typescript/src/string/str_repeat.ts
> + * @param times - Number of time the `str` string should be repeated. `times` has to be greater than or equal to 0. If the `times` is set to 0, the function will return an empty string.
tambahin tes kalo times nya itu negatif

2022-10-08 04:31 UTC, aldy505 commented on typescript/src/string/chr.ts
> + * @param ascii - An integer between 0 and 255.
tambahin tes kalo ascii number ini < 0 dan > 255

2022-10-08 04:45 UTC, afman42 commented on typescript/src/string/str_repeat.ts
> + * @param times - Number of time the `str` string should be repeated. `times` has to be greater than or equal to 0. If the `times` is set to 0, the function will return an empty string.
ini udah di merged sama @elianiva

2022-10-08 04:45 UTC, afman42 commented on typescript/src/string/chr.ts
> + * @param ascii - An integer between 0 and 255.
oke pak

2022-10-08 04:58 UTC, elianiva commented on typescript/src/string/str_repeat.ts
> + * @param times - Number of time the `str` string should be repeated. `times` has to be greater than or equal to 0. If the `times` is set to 0, the function will return an empty string.
sekalian tambahin di PR ini

2022-10-08 04:58 UTC, afman42 commented on typescript/src/string/str_repeat.ts
> + * @param times - Number of time the `str` string should be repeated. `times` has to be greater than or equal to 0. If the `times` is set to 0, the function will return an empty string.
oke kak

2022-10-09 05:01 UTC, afman42 commented on typescript/src/string/chr.ts
> + * @param ascii - An integer between 0 and 255.
silakan cek lagi pak @aldy505

2022-10-10 03:05 UTC, aldy505 approved these changes

2022-10-10 03:05 UTC, merged