Feat typescript/str split
teknologi-umum/pehape pull request #68
Opened 2022-10-10 06:53 UTC by nblfikr

- Programming langugage: Typescript
- Function(s) that I'm implementing: str_split
- Issue number: #18 

- [x] I have created unit tests to support my implementation
- [x] I have created in-code documentation (or docstring) to document my code
- [ ] (Optional) I have updated the README.md file to document the function I'm implementing

ini hasil testnya
![image](https://user-images.githubusercontent.com/56732307/194811516-48c05d3d-35dd-48e4-991a-624d30894ee4.png)

2022-10-11 10:45 UTC, elianiva requested changes

2022-10-11 10:45 UTC, elianiva commented on typescript/src/string/str_split.ts
> + * @param str - The string to be convert.
```suggestion
 * @param str - The input string.
```

2022-10-11 10:45 UTC, elianiva commented on typescript/src/string/str_split.ts
> +    if (typeof str === "undefined" || typeof str !== "string") return false;
redundant ini checknya, langsung cek kalo str itu bukan string aja, ga perlu `typeof str === "undefined"`

2022-10-11 10:45 UTC, elianiva commented on typescript/src/string/str_split.ts
> +    if (typeof len !== "undefined" && typeof len === "number") {
ini juga, ngga perlu cek kalo `len` itu bukan undefined

2022-10-11 10:45 UTC, elianiva commented on typescript/src/string/str_split.ts
> +    return str.split("");
jadiin 1 implementasi aja bisa ngga? jadi daripada ada branch yg misahin antara implementasi pake loop sama `.split()`, mending `len` jadiin 1 biar bisa pake loop yg sama

2022-10-11 10:53 UTC, nblfikr commented on typescript/src/string/str_split.ts
> +    return str.split("");
maksutnya value defaultnya `len` satu gitu ya, sama ilangin `.split()`?

2022-10-11 14:54 UTC, elianiva commented on typescript/src/string/str_split.test.ts
> +describe("string split", () => {
tambahin test buat handle kalo `len` itu bukan number

2022-10-11 22:05 UTC, elianiva commented on typescript/src/string/str_split.test.ts
> +describe("string split", () => {
pake @ts-expect-error

2022-10-12 07:25 UTC, nblfikr commented on typescript/src/string/str_split.test.ts
> +describe("string split", () => {
early return gmana mas?

2022-10-12 14:58 UTC, elianiva commented on typescript/src/string/str_split.test.ts
> +describe("string split", () => {
sekarang kan bentuknya gini
```typescript
if (typeof foo === "number") {
    // logic panjang disini
}

return false
```

kamu balik jadi gini
```typescript
if (typeof foo !== "number") return false;

// logic panjang disini
```

2022-10-17 05:45 UTC, aldy505 commented
jalanin `pnpm run lint:fix`

2022-10-17 05:55 UTC, nblfikr commented
sudah mas @aldy505

2022-10-18 09:35 UTC, elianiva approved these changes

2022-10-18 09:35 UTC, merged