feat(TypeScript): count_chars
teknologi-umum/pehape pull request #70
Opened 2022-10-29 16:36 UTC by DimensionalDragon

- Programming langugage: TypeScript
- Function(s) that I'm implementing: count_chars
- Issue number: #18 

- [x] I have created unit tests to support my implementation
- [x] I have created in-code documentation (or docstring) to document my code
- [ ] (Optional) I have updated the README.md file to document the function I'm implementing

2022-10-30 02:23 UTC, elianiva requested changes

2022-10-30 02:23 UTC, elianiva commented on typescript/src/string/count_chars.ts
> +      return false;
it should throw instead of returning false

2022-10-31 12:36 UTC, aldy505 approved these changes
LGTM

2022-10-31 12:42 UTC, elianiva approved these changes

2022-10-31 12:42 UTC, merged